# Generated by Django 5.2.5 on 2025-09-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('dni_alumno', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_alumno', models.CharField(max_length=35)),
                ('apellido_alumno', models.CharField(max_length=35)),
                ('fecha_nacimiento_alumno', models.DateField(blank=True, null=True)),
                ('genero_alumno', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True)),
            ],
            options={
                'db_table': 'alumnos',
                'ordering': ['apellido_alumno', 'nombre_alumno'],
            },
        ),
    ]
