# Generated by Django 5.2.5 on 2025-09-04 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('dni_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_empleado', models.CharField(max_length=35)),
                ('apellido_empleado', models.CharField(max_length=35)),
                ('telefono_empleado', models.CharField(max_length=15)),
                ('email_empleado', models.EmailField(max_length=50)),
                ('genero_empleado', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
            ],
            options={
                'db_table': 'empleados',
                'ordering': ['apellido_empleado', 'nombre_empleado'],
            },
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id_parentesco', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco_nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'parentescos',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['nombre_rol'],
            },
        ),
        migrations.CreateModel(
            name='Tutores',
            fields=[
                ('dni_tutor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_tutor', models.CharField(max_length=35)),
                ('apellido_tutor', models.CharField(max_length=35)),
                ('telefono_tutor', models.CharField(max_length=15)),
                ('email_tutor', models.EmailField(max_length=50)),
                ('genero_tutor', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
            ],
            options={
                'db_table': 'tutores',
                'ordering': ['apellido_tutor', 'nombre_tutor'],
            },
        ),
        migrations.CreateModel(
            name='Grados',
            fields=[
                ('id_grado', models.IntegerField(choices=[(1, '1 Año'), (2, '2 Año'), (3, '3 Año'), (4, '4 Año'), (5, '5 Año')], primary_key=True, serialize=False)),
                ('nombre_grado', models.CharField(max_length=50)),
                ('asientos_disponibles', models.IntegerField()),
                ('dni_empleado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='secretaria.empleados')),
            ],
            options={
                'db_table': 'grados',
                'ordering': ['id_grado'],
            },
        ),
        migrations.AddField(
            model_name='empleados',
            name='id_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='secretaria.roles'),
        ),
        migrations.CreateModel(
            name='Alumnos_X_Grados',
            fields=[
                ('id_alumno_x_grado', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('dni_alumno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='secretaria.alumno')),
                ('id_grado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='secretaria.grados')),
            ],
            options={
                'db_table': 'alumnos_x_grados',
                'ordering': ['dni_alumno', 'id_grado'],
                'unique_together': {('dni_alumno', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='Alumnos_X_Tutores',
            fields=[
                ('id_alumno_x_tutor', models.AutoField(primary_key=True, serialize=False)),
                ('dni_alumno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='secretaria.alumno')),
                ('id_parentesco', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='secretaria.parentesco')),
                ('dni_tutor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='secretaria.tutores')),
            ],
            options={
                'db_table': 'alumnos_x_tutores',
                'ordering': ['dni_alumno', 'dni_tutor'],
                'unique_together': {('dni_alumno', 'dni_tutor')},
            },
        ),
    ]
