# Generated by Django 5.2.5 on 2025-09-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0002_empleados_parentesco_roles_tutores_grados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grados',
            name='dni_empleado',
        ),
        migrations.AlterField(
            model_name='grados',
            name='id_grado',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
